ComputersStore/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputersStore.BusinessServices.Interfaces;
using ComputersStore.Data.Dictionaries;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputersStore.WebUI.Controllers
{
    [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
    public class ApplicationUsersController : Controller
    {
        #region Fields

        private readonly IApplicationUserBusinessService applicationUserBusinessService;
        private readonly int applicationUserPerPage = 5;

        #endregion Fields

        #region Constructors

        public ApplicationUsersController(IApplicationUserBusinessService applicationUserBusinessService)
        {
            this.applicationUserBusinessService = applicationUserBusinessService;
        }

        #endregion Constrctors

        #region Actions

        // GET: ApplicationUsers/Customers
        public async Task<IActionResult> Customers(string firstName, string lastName, string email, string phoneNumber, int pageNumber = 1)
        {
            var usersCollectionViewModel = await applicationUserBusinessService.GetApplicationUsersFilteredCollection(ApplicationUserRoleDictionary.Customer, firstName, lastName, email, phoneNumber, pageNumber, applicationUserPerPage);
            return View(usersCollectionViewModel);
        }

        // GET: ApplicationUsers/Admins
        public async Task<IActionResult> Admins(string firstName, string lastName, string email, string phoneNumber, int pageNumber = 1)
        {
            var adminsCollectionViewModel = await applicationUserBusinessService.GetApplicationUsersFilteredCollection(ApplicationUserRoleDictionary.Admin, firstName, lastName, email, phoneNumber, pageNumber, applicationUserPerPage);
            return View(adminsCollectionViewModel);
        }

        // GET: ApplicationUsers/Delete/5
        public async Task<IActionResult> Delete(string applicationUserId)
        {
            if (applicationUserId == null)
            {
                return NotFound();
            }

            var applicationUserViewModel = await applicationUserBusinessService.GetApplicationUserById(applicationUserId);
            if (applicationUserViewModel == null)
            {
                return NotFound();
            }

            return PartialView("~/Views/ApplicationUsers/Modals/_DeleteApplicationUserModal.cshtml", applicationUserViewModel);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string applicationUserId)
        {
            await applicationUserBusinessService.DeleteApplicationUser(applicationUserId);
            return Json( new { success = true});
        }

        // GET: ApplicationUsers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var applicationUserViewModel = await applicationUserBusinessService.GetApplicationUserById(id);
            return View(applicationUserViewModel);
        }

        #endregion Actions
    }
}

ComputersStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ComputersStore.Data.Entities;
using ComputersStore.Data;
using ComputersStore.BusinessServices.Interfaces;
using ComputersStore.Database.DatabaseContext;
using ComputersStore.Models.ViewModels.Order;
using ComputersStore.EmailHelper.Service.Interface;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using ComputersStore.Data.Dictionaries;
using ComputersStore.Models.ViewModels.Order.Base;

namespace ComputersStore.WebUI.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        #region Fields

        private readonly IOrderBusinessService orderBusinessService;
        private readonly IOrderStatusBusinessService orderStatusBusinessService;
        private readonly IPaymentTypeBusinessService paymentTypeBusinessService;
        private readonly IApplicationUserBusinessService applicationUserBusinessService;
        private readonly IEmailService emailService;
        private readonly int ordersPerPage = 5;

        #endregion Fields

        #region Constructors

        public OrdersController(IOrderBusinessService orderBusinessService, IOrderStatusBusinessService orderStatusBusinessService, IPaymentTypeBusinessService paymentTypeBusinessService, IApplicationUserBusinessService applicationUserBusinessService, IEmailService emailService)
        {
            this.orderBusinessService = orderBusinessService;
            this.orderStatusBusinessService = orderStatusBusinessService;
            this.paymentTypeBusinessService = paymentTypeBusinessService;
            this.applicationUserBusinessService = applicationUserBusinessService;
            this.emailService = emailService;
        }

        #endregion Constructors 

        #region Actions

        // GET: Orders/Table
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        public async Task<IActionResult> Table(int? orderId, int? orderStatusId, int? paymentTypeId, string applicationUserEmail, int pageNumber = 1)
        {
            var orders = await orderBusinessService.GetOrdersFilteredCollection(orderId, orderStatusId, paymentTypeId, applicationUserEmail, pageNumber, ordersPerPage, ordersPerPage);
            await PopulateUpdateFormSelectElements(orderStatusId, paymentTypeId);
            return View(orders);
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await orderBusinessService.GetOrderDetails(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await orderBusinessService.GetOrderEditData(id.Value);
            
            if (order == null)
            {
                return NotFound();
            }

            await PopulateUpdateFormSelectElements(order.OrderStatusId, order.PaymentTypeId);
            
            return View(order);
        }

        // POST: Orders/Edit/5
        [HttpPost]
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderEditFormViewModel orderEditFormViewModel)
        {
            if (id != orderEditFormViewModel.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await orderBusinessService.UpdateOrder(orderEditFormViewModel);
                return RedirectToAction(nameof(Table));
            }
            await PopulateUpdateFormSelectElements(orderEditFormViewModel.OrderStatusId, orderEditFormViewModel.PaymentTypeId);
            return View(orderEditFormViewModel);
        }

        // GET: Orders/ChangeStatus/5
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        public async Task<IActionResult> ChangeStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await orderBusinessService.GetOrder(id.Value);

            if (order == null)
            {
                return NotFound();
            }

            await PopulateChangeOrdersStatusFormSelectElements(order.OrderStatusId);
            return PartialView("~/Views/Orders/Modals/_ChangeOrderStatusModal.cshtml" ,order);
        }

        // POST: Orders/ChangeStatus/5
        [HttpPost]
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeStatus(int id, int orderStatusId)
        {
            await orderBusinessService.UpdateOrderStatus(id, orderStatusId);
            await SendOrderStatusChangedEmail(id);
            return Json( new { success = true });
        }

        // GET: Orders/Delete/5
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await orderBusinessService.GetOrder(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            return PartialView("~/Views/Orders/Modals/_DeleteOrderModal.cshtml", order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await orderBusinessService.DeleteOrder(id);
            return RedirectToAction(nameof(Table));
        }

        #endregion Actions

        #region Helpers

        private async Task PopulateUpdateFormSelectElements(int? orderStatusId, int? paymentTypeId)
        {
            var orderStatuses = await orderStatusBusinessService.GetOrderStatusesCollection();
            var paymentTypes = await paymentTypeBusinessService.GetPaymentTypesCollection();
            ViewData["OrderStatuses"] = new SelectList(orderStatuses, "OrderStatusId", "Name", orderStatusId);
            ViewData["PaymentTypes"] = new SelectList(paymentTypes, "PaymentTypeId", "Name", paymentTypeId);
        }

        private async Task PopulateChangeOrdersStatusFormSelectElements(int? orderStatusId)
        {
            var orderStatuses = await orderStatusBusinessService.GetOrderStatusesCollection();
            ViewData["OrderStatuses"] = new SelectList(orderStatuses, "OrderStatusId", "Name", orderStatusId);
        }

        private async Task SendOrderStatusChangedEmail(int orderId)
        {
            var updatedOrder = await orderBusinessService.GetOrderDetails(orderId);
            await emailService.SendOrderStatusChangedEmail(updatedOrder.ApplicationUserViewModel.Email, updatedOrder.ApplicationUserViewModel.FirstName, updatedOrder.OrderViewModel.OrderId, updatedOrder.OrderViewModel.OrderStatusName);
        }

        #endregion Helpers

    }
}

ComputersStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ComputersStore.Data.Entities;
using ComputersStore.Data;
using ComputersStore.BusinessServices.Interfaces;
using ComputersStore.Database.DatabaseContext;
using ComputersStore.Data.Dictionaries;
using ComputersStore.Models.ViewModels.Product;
using ComputersStore.Models.ViewModels.Other;
using Microsoft.AspNetCore.Authorization;
using ComputersStore.Models.ViewModels.Product.Base;
using ComputersStore.Models.ViewModels.Product.Complex;

namespace ComputersStore.WebUI.Controllers
{
    [Authorize(Roles = ApplicationUserRoleDictionary.Admin)]
    public class ProductsController : Controller
    {
        #region Fields

        private readonly IProductBusinessService productBusinessService;
        private readonly IProductCategoryBusinessService productCategoryBusinessService;
        private readonly int productsPerPage = 5;

        #endregion Fields

        #region Constructors

        public ProductsController(IProductBusinessService productBusinessService, IProductCategoryBusinessService productCategoryBusinessService)
        {
            this.productBusinessService = productBusinessService;
            this.productCategoryBusinessService = productCategoryBusinessService;
        }

        #endregion Constructors

        #region Actions

        // GET: Products/List
        [AllowAnonymous]
        public async Task<ActionResult> List(int productCategoryId, int pageNumber = 1, string sortOrder = null)
        {
            var productsCollectionViewModel = await productBusinessService.GetProductsCollection(productCategoryId, sortOrder, pageNumber, productsPerPage);
            return View(productsCollectionViewModel);
        }

        // GET: Products/ChooseNewProductCategory
        public async Task<IActionResult> ChooseNewProductCategory()
        {
            await PassProductsCategoriesSelectListToView(null);
            return View();
        }

        // POST: Products/ChooseNewProductCategory
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChooseNewProductCategory(NewProductCategoryFormViewModel productCategoryFormViewModel)
        {
            return RedirectToAction(nameof(Create), new { productCategoryId = productCategoryFormViewModel.ProductCategoryId });
        }

        // GET: Products/Table
        public async Task<IActionResult> Table(int? productCategoryId, string productName, bool? isRecommended, int pageNumber = 1)
        {
            var productsTableViewModel = await productBusinessService.GetProductsFilteredCollection(productCategoryId, productName, isRecommended, pageNumber, productsPerPage);
            await PassProductsCategoriesSelectListToView(productCategoryId);
            return View(productsTableViewModel);
        }

        // GET: Products/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var productDetailsViewModel = await productBusinessService.GetProductDetails(id);
            if (productDetailsViewModel == null)
            {
                return NotFound();
            }
            return View(productDetailsViewModel);
        }

        // GET: Products/Create
        public IActionResult Create(int productCategoryId)
        {
            var newProductViewModel = productBusinessService.PrepareNewEmptyProduct(productCategoryId);
            return View(newProductViewModel);
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateFormViewModel newProductViewModel)
        {
            if (ModelState.IsValid)
            {
                await productBusinessService.CreateProduct(newProductViewModel);
                return RedirectToAction(nameof(Table));
            }
            return View(newProductViewModel);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var productEditFormViewModel = await productBusinessService.GetProductEditData(id);
            if (productEditFormViewModel == null)
            {
                return NotFound();
            }
            return View(productEditFormViewModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductEditFormViewModel productsDetailsViewModel)
        {
            if (id != productsDetailsViewModel.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await productBusinessService.UpdateProduct(productsDetailsViewModel);
                return RedirectToAction(nameof(Table));
            }
            return View(productsDetailsViewModel);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await productBusinessService.GetProduct(id.Value);
            if (product == null)
            {
                return NotFound();
            }

            return PartialView("~/Views/Products/Modals/_DeleteProductModal.cshtml", product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productBusinessService.DeleteProduct(id);
            return RedirectToAction(nameof(List));
        }

        // POST: Products/SearchProducts
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchProducts(string searchString)
        {
            var searchedProductsCollectionViewModel = await productBusinessService.GetProductsSearchedCollection(searchString);
            return View(searchedProductsCollectionViewModel);
        }

        #endregion Actions

        #region Helpers

        public async Task PassProductsCategoriesSelectListToView(int? productCategory)
        {
            var productCategories = await productCategoryBusinessService.GetProductsCategoriesCollection();
            ViewData["ProductsCategories"] = new SelectList(productCategories, "ProductCategoryId", "Name", productCategory);
        }

        #endregion Helpers
    }
}

ComputersStore/Views/Shared/_AdminLinksPanelPartial.cshtml
<ul class="navbar-nav">
        <li class="nav-item text-white d-flex justify-content-center align-items-center">
            @User.Identity.Name
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-controller="Account" asp-action="LogOff">
                <button type="submit" class="nav-link btn btn-link text-white">Logout</button>
            </form>
        </li>
</ul>

ComputersStore/Views/Shared/_AdminNavbarPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black text-white border-bottom box-shadow fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand h1 mb-0" asp-controller="Home" asp-action="Index">ComputersStore Admin Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="productsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>
                    <div class="dropdown-menu bg-black" aria-labelledby="productsDropdown">
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.CPU">CPU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.GPU">GPU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.Motherboard">Motherboard</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.RAM">RAM</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.PSU">PSU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.HDD">HDD</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.SSD">SSD</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Orders" asp-action="Table">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="ApplicationUsers" asp-action="Users">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="ApplicationUsers" asp-action="Admins">Admins</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="newslettersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Newsletters
                    </a>
                    <div class="dropdown-menu bg-black" aria-labelledby="newslettersDropdown">
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Newsletters" asp-action="SendNewsletter">Send newsletter</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Newsletters" asp-action="Table">Table</a>
                    </div>
                </li>
            </ul>
            <partial name="_AdminLinksPanelPartial" />
        </div>
    </div>
</nav>

ComputersStore/Views/Shared/_DesktopLinksMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<a href="" class="d-flex flex-column align-items-center justify-content-between text-white h-100 py-2 px-2 navbar-desktop-user-link">
    <i class="fa fa-globe-americas"></i>
    <span class="navbar-desktop-user-link-caption">Language</span>
</a>
<a href="#" data-toggle="dropdown" class="d-flex flex-column align-items-center justify-content-between text-white h-100 py-2 px-2 navbar-desktop-user-link">
    <i class="fa fa-user"></i>
    <span class="navbar-desktop-user-link-caption">Account</span>
</a>
@if (SignInManager.IsSignedIn(User))
{
    <div class="dropdown-menu account-dropdown-menu p-0 rounded-0">
        <div class="w-100 bg-light-ashen d-flex flex-column justify-content-center p-4">
            <h5 class="mb-3">@User.Identity.Name</h5>
            <form class="form-inline" asp-controller="Account" asp-action="LogOff">
                <button type="submit" class="btn btn-green btn-sm text-uppercase">Logout</button>
            </form>
        </div>
        <div class="w-100 bg-white d-flex flex-column justify-content-center p-4">
            <ul class="list-unstyled">
                <li><i class="fa fa-box mr-2"></i><a asp-controller="Account" asp-action="ApplicationUserOrders" class="account-panel-link" account-panel-link>My orders</a></li>
                <li><i class="fa fa-user-edit mr-2"></i><a asp-controller="Account" asp-action="UpdateAccountData" class="account-panel-link" account-panel-link>My data</a></li>
                <li><i class="fa fa-key mr-2"></i><a asp-controller="Account" asp-action="ChangePassword" class="account-panel-link" account-panel-link>Change password</a></li>
            </ul>
        </div>

    </div>
}
else
{
    <div class="dropdown-menu account-dropdown-menu p-0 rounded-0">
        <div class="w-100 bg-light-ashen d-flex flex-column justify-content-center p-4">
            <h5 class="mb-3">Are you a user?</h5>
            <a class="btn btn-green w-75" asp-controller="Account" asp-action="Login">Log in</a>
        </div>
        <div class="w-100 bg-white d-flex flex-column justify-content-center p-4">
            <h5 class="mb-3">Is it your first visit?</h5>
            <a class="btn btn-transparent-green w-75" asp-controller="Account" asp-action="Register">Create account</a>
        </div>

    </div>
}
<a asp-controller="ShoppingCart" asp-action="Summary" class="d-flex flex-column align-items-center justify-content-between text-white h-100 py-2 px-2 navbar-desktop-user-link">
    <i class="fa fa-shopping-cart"></i>
    <span class="navbar-desktop-user-link-caption">Shopping</span>
</a>

ComputersStore/Views/Shared/_DesktopNavbarPartial.cshtml
<nav class="navbar navbar-dark p-0 d-none d-sm-flex" fixed-top-nav>
    <div class="container-fluid d-flex flex-column p-0">
        <div class="row w-100 bg-black px-2 py-3">
            <div class="col-2 d-flex justify-content-start align-items-center">
                <form class="form-group w-100 m-0" asp-controller="Products" asp-action="SearchProducts" method="post">
                    <div class="input-group navbar-search-products-input-group pb-1">
                        <input class="form-control w-75 navbar-search-product-input shadow-none px-0 text-white" placeholder="Search" aria-label="Search" name="SearchString">
                        <div class="input-group-append w-25">
                            <button class="btn text-white w-100 bg-black" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-8 d-flex justify-content-center align-items-center">
                <a class="h1 text-white text-decoration-none" asp-controller="Home" asp-action="Index">ComputersStore</a>
            </div>
            <div class="col-2 d-flex justify-content-end align-items-center">
                <partial name="_DesktopLinksMenuPartial" />
            </div>
        </div>
        <div class="row d-flex justify-content-center w-100 bg-dark-grey px-2 py-3">
            <div class="w-50 d-flex justify-content-around align-items-center">
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.CPU">CPU</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.GPU">GPU</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.Motherboard">Motherboard</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.RAM">RAM</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.PSU">PSU</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.HDD">HDD</a>
                <a class="navbar-desktop-product-category-link" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.SSD">SSD</a>
            </div>
        </div>
    </div>
</nav>

ComputersStore/Views/Shared/_MobileNavbarPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black text-white border-bottom box-shadow fixed-top d-flex d-sm-none">
    <div class="container-fluid">
        <a class="navbar-brand h1 mb-0" asp-area="" asp-controller="Home" asp-action="Index">ComputersStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>
                    <div class="dropdown-menu bg-black" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.CPU">CPU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.GPU">GPU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.Motherboard">Motherboard</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.RAM">RAM</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.PSU">PSU</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.HDD">HDD</a>
                        <a class="dropdown-item navbar-dropdown-product-item" asp-controller="Products" asp-action="List" asp-route-productCategoryId="@ProductCategoryDictionary.SSD">SSD</a>
                    </div>
                </li>
            </ul>
            <partial name="_MobileLinksMenuPartial" />
        </div>
    </div>
</nav>